# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import pbft_pb2 as pbft__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in pbft_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PBFTStub(object):
    """
    pBFT Protocol Definition
    Implements the three-phase commit protocol: Pre-prepare, Prepare, Commit

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PrePrepare = channel.unary_unary(
                '/PBFT/PrePrepare',
                request_serializer=pbft__pb2.PrePrepareRequest.SerializeToString,
                response_deserializer=pbft__pb2.PrePrepareResponse.FromString,
                _registered_method=True)
        self.Prepare = channel.unary_unary(
                '/PBFT/Prepare',
                request_serializer=pbft__pb2.PrepareRequest.SerializeToString,
                response_deserializer=pbft__pb2.PrepareResponse.FromString,
                _registered_method=True)
        self.Commit = channel.unary_unary(
                '/PBFT/Commit',
                request_serializer=pbft__pb2.CommitRequest.SerializeToString,
                response_deserializer=pbft__pb2.CommitResponse.FromString,
                _registered_method=True)
        self.ClientSubmitBlock = channel.unary_unary(
                '/PBFT/ClientSubmitBlock',
                request_serializer=pbft__pb2.ClientBlockRequest.SerializeToString,
                response_deserializer=pbft__pb2.ClientBlockResponse.FromString,
                _registered_method=True)
        self.GetBlockchain = channel.unary_unary(
                '/PBFT/GetBlockchain',
                request_serializer=pbft__pb2.Empty.SerializeToString,
                response_deserializer=pbft__pb2.BlockchainResponse.FromString,
                _registered_method=True)
        self.GetNodeStatus = channel.unary_unary(
                '/PBFT/GetNodeStatus',
                request_serializer=pbft__pb2.Empty.SerializeToString,
                response_deserializer=pbft__pb2.NodeStatusResponse.FromString,
                _registered_method=True)
        self.SetMaliciousBehavior = channel.unary_unary(
                '/PBFT/SetMaliciousBehavior',
                request_serializer=pbft__pb2.MaliciousConfigRequest.SerializeToString,
                response_deserializer=pbft__pb2.MaliciousConfigResponse.FromString,
                _registered_method=True)


class PBFTServicer(object):
    """
    pBFT Protocol Definition
    Implements the three-phase commit protocol: Pre-prepare, Prepare, Commit

    """

    def PrePrepare(self, request, context):
        """===== pBFT CORE PROTOCOL =====
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Prepare(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Commit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClientSubmitBlock(self, request, context):
        """===== CLIENT API =====
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBlockchain(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNodeStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetMaliciousBehavior(self, request, context):
        """===== BYZANTINE FAULT SIMULATION =====
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PBFTServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PrePrepare': grpc.unary_unary_rpc_method_handler(
                    servicer.PrePrepare,
                    request_deserializer=pbft__pb2.PrePrepareRequest.FromString,
                    response_serializer=pbft__pb2.PrePrepareResponse.SerializeToString,
            ),
            'Prepare': grpc.unary_unary_rpc_method_handler(
                    servicer.Prepare,
                    request_deserializer=pbft__pb2.PrepareRequest.FromString,
                    response_serializer=pbft__pb2.PrepareResponse.SerializeToString,
            ),
            'Commit': grpc.unary_unary_rpc_method_handler(
                    servicer.Commit,
                    request_deserializer=pbft__pb2.CommitRequest.FromString,
                    response_serializer=pbft__pb2.CommitResponse.SerializeToString,
            ),
            'ClientSubmitBlock': grpc.unary_unary_rpc_method_handler(
                    servicer.ClientSubmitBlock,
                    request_deserializer=pbft__pb2.ClientBlockRequest.FromString,
                    response_serializer=pbft__pb2.ClientBlockResponse.SerializeToString,
            ),
            'GetBlockchain': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBlockchain,
                    request_deserializer=pbft__pb2.Empty.FromString,
                    response_serializer=pbft__pb2.BlockchainResponse.SerializeToString,
            ),
            'GetNodeStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNodeStatus,
                    request_deserializer=pbft__pb2.Empty.FromString,
                    response_serializer=pbft__pb2.NodeStatusResponse.SerializeToString,
            ),
            'SetMaliciousBehavior': grpc.unary_unary_rpc_method_handler(
                    servicer.SetMaliciousBehavior,
                    request_deserializer=pbft__pb2.MaliciousConfigRequest.FromString,
                    response_serializer=pbft__pb2.MaliciousConfigResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'PBFT', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('PBFT', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PBFT(object):
    """
    pBFT Protocol Definition
    Implements the three-phase commit protocol: Pre-prepare, Prepare, Commit

    """

    @staticmethod
    def PrePrepare(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/PBFT/PrePrepare',
            pbft__pb2.PrePrepareRequest.SerializeToString,
            pbft__pb2.PrePrepareResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Prepare(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/PBFT/Prepare',
            pbft__pb2.PrepareRequest.SerializeToString,
            pbft__pb2.PrepareResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Commit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/PBFT/Commit',
            pbft__pb2.CommitRequest.SerializeToString,
            pbft__pb2.CommitResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClientSubmitBlock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/PBFT/ClientSubmitBlock',
            pbft__pb2.ClientBlockRequest.SerializeToString,
            pbft__pb2.ClientBlockResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBlockchain(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/PBFT/GetBlockchain',
            pbft__pb2.Empty.SerializeToString,
            pbft__pb2.BlockchainResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetNodeStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/PBFT/GetNodeStatus',
            pbft__pb2.Empty.SerializeToString,
            pbft__pb2.NodeStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetMaliciousBehavior(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/PBFT/SetMaliciousBehavior',
            pbft__pb2.MaliciousConfigRequest.SerializeToString,
            pbft__pb2.MaliciousConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
